# Generated by Django 3.1.7 on 2021-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210727_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(default='home', max_length=200),
            preserve_default=False,
        ),
    ]
